from dataclasses import dataclass


@dataclass
class DailyReviewSnapshot:
    """
    Historical record of a FreedomIQ daily portfolio review.

    Stores the investor-facing review generated by the
    existing Daily Portfolio Review engine.

    This model does not perform any investment analysis.
    """

    review_date: str

    portfolio_status: dict

    changes: list[dict]
    actions: list[dict]
    opportunities: list[dict]
    watchpoints: list[dict]

    conclusion: str